# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'permissions': (('view_lancamento', 'Can view lancamento'),), 'verbose_name': 'Lançamento'},
        ),
        migrations.AlterModelOptions(
            name='movimentocaixa',
            options={'permissions': (('acesso_fluxodecaixa', 'Pode acessar o Fluxo de Caixa'),), 'verbose_name': 'Movimento de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='planocontasgrupo',
            options={'permissions': (('view_planocontasgrupo', 'Can view plano contas'),), 'verbose_name': 'Grupo do Plano de Contas'},
        ),
    ]
