# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontassubgrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='financeiro.PlanoContasGrupo'),
        ),
    ]
