# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20170625_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhaempresa',
            name='m_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to='login.Usuario'),
        ),
    ]
