# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20170714_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('view_categoria', 'Can view categoria'),), 'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('view_cliente', 'Can view cliente'),), 'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': (('view_empresa', 'Can view empresa'),), 'verbose_name': 'Empresa'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'permissions': (('view_fornecedor', 'Can view fornecedor'),), 'verbose_name': 'Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'permissions': (('view_marca', 'Can view marca'),), 'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': (('view_produto', 'Can view produto'),), 'verbose_name': 'Produto'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'permissions': (('view_transportadora', 'Can view transportadora'),), 'verbose_name': 'Transportadora'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'permissions': (('view_unidade', 'Can view unidade'),), 'verbose_name': 'Unidade'},
        ),
    ]
