# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 17:50
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13,
                                                   null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=13,
                                                 null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1055)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(blank=True, null=True)),
                ('quantidade_itens', models.IntegerField(default=0,
                                                         validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.CharField(
                    blank=True, max_length=1055, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstocado',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='local_produto_estocado', to='estoque.LocalEstoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='produto_estocado', to='cadastro.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                              parent_link=True, primary_key=True, serialize=False, to='estoque.MovimentoEstoque')),
                ('tipo_movimento', models.CharField(choices=[('0', 'Ajuste'), ('1', 'Entrada por pedido de compra'), (
                    '2', 'Entrada por importação de nota fiscal de fornecedor'), ('3', 'Ajuste inicial')], default='0', max_length=1)),
            ],
            bases=('estoque.movimentoestoque',),
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                              parent_link=True, primary_key=True, serialize=False, to='estoque.MovimentoEstoque')),
                ('tipo_movimento', models.CharField(choices=[('0', 'Ajuste'), ('1', 'Saída por pedido de venda'), (
                    '2', 'Saída por importação de nota fiscal')], default='0', max_length=1)),
            ],
            bases=('estoque.movimentoestoque',),
        ),
        migrations.CreateModel(
            name='TransferenciaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                              parent_link=True, primary_key=True, serialize=False, to='estoque.MovimentoEstoque')),
            ],
            bases=('estoque.movimentoestoque',),
        ),
        migrations.AddField(
            model_name='localestoque',
            name='produtos_estoque',
            field=models.ManyToManyField(
                through='estoque.ProdutoEstocado', to='cadastro.Produto'),
        ),
        migrations.AddField(
            model_name='itensmovimento',
            name='movimento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='itens_movimento', to='estoque.MovimentoEstoque'),
        ),
        migrations.AddField(
            model_name='itensmovimento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='moviment_estoque_produto', to='cadastro.Produto'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_estoque_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transf_estoque_dest', to='estoque.LocalEstoque'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_estoque_orig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transf_estoque_orig', to='estoque.LocalEstoque'),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='local_orig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='saida_estoque_local', to='estoque.LocalEstoque'),
        ),
    ]
