# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        ('cadastro', '0001_initial'),
        ('compras', '0002_auto_20170625_1450'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='saida_estoque', to='vendas.PedidoVenda'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='entrada_estoque_fornecedor', to='cadastro.Fornecedor'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='entrada_estoque_local', to='estoque.LocalEstoque'),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='entrada_estoque_pedido', to='compras.PedidoCompra'),
        ),
    ]
