# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial_data'),
        ('estoque', '0002_auto_20170625_1450'),
    ]

    operations = [
    ]
