# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_merge_20170625_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localestoque',
            options={'permissions': (('view_localestoque', 'Can view local estoque'),), 'verbose_name': 'Local de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={'permissions': (('view_movimentoestoque', 'Can view movimento estoque'), ('consultar_estoque', 'Pode consultar estoque')), 'verbose_name': 'Movimento de Estoque'},
        ),
    ]
