# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaonotafiscal',
            options={'default_permissions': (), 'permissions': (('view_configuracaonotafiscal', 'Can view configuracao nota fiscal'), ('configurar_nfe', 'Pode modificar configuração de NF-e')), 'verbose_name': 'Configuração NF-e'},
        ),
        migrations.AlterModelOptions(
            name='grupofiscal',
            options={'permissions': (('view_grupofiscal', 'Can view grupo fiscal'),), 'verbose_name': 'Grupo Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='naturezaoperacao',
            options={'permissions': (('view_naturezaoperacao', 'Can view natureza operacao'),), 'verbose_name': 'Natureza da Operação'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalentrada',
            options={'permissions': (('view_notafiscalentrada', 'Can view nota fiscal entrada'),), 'verbose_name': 'Nota Fiscal de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalsaida',
            options={'permissions': (('view_notafiscal', 'Can view nota fiscal'), ('emitir_notafiscal', 'Pode emitir notas fiscais'), ('cancelar_notafiscal', 'Pode cancelar notas fiscais'), ('gerar_danfe', 'Pode gerar DANFE/DANFCE'), ('consultar_cadastro', 'Pode consultar cadastro no SEFAZ'), ('inutilizar_notafiscal', 'Pode inutilizar notas fiscais'), ('consultar_notafiscal', 'Pode consultar notas fiscais'), ('baixar_notafiscal', 'Pode baixar notas fiscais'), ('manifestacao_destinatario', 'Pode efetuar manifestação do destinatário')), 'verbose_name': 'Nota Fiscal'},
        ),
    ]
