# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicaopagamento',
            options={'permissions': (('view_condicaopagamento', 'Can view condicao pagamento'),), 'verbose_name': 'Condição de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='orcamentovenda',
            options={'permissions': (('view_orcamentovenda', 'Can view orcamento venda'),), 'verbose_name': 'Orçamento de Venda'},
        ),
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'permissions': (('view_pedidovenda', 'Can view pedido venda'), ('faturar_pedidovenda', 'Pode faturar Pedidos de Venda')), 'verbose_name': 'Pedido de Venda'},
        ),
    ]
